### PR TITLE
1-TwoSum

### LINKED ISSUE #4: 1. Two Sum
Given an array of integers `nums` and an integer `target`, return _indices of the two numbers such that they add up to `target`_.

You may assume that each input would have **_exactly_ one solution**, and you may not use the _same_ element twice.

You can return the answer in any order.

**Example 1:**

```
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].
```

**Example 2:**

```
Input: nums = [3,2,4], target = 6
Output: [1,2]
```

**Example 3:**

```
Input: nums = [3,3], target = 6
Output: [0,1]
```

**Constraints:**

* 2 <= nums.length <= 10<sup>4</sup>
* -10<sup>9</sup> <= nums[i] <= 10<sup>9</sup>
* -10<sup>9</sup> <= target <= 10<sup>9</sup>
* **Only one valid answer exists.*

**Code structure:**
```csharp
public class Solution {
    public int[] TwoSum(int[] nums, int target) {
        //your code goes here
    }
}
```

### PR DESCRIPTION
**Pull request by LoLProM**

### CODE REVIEW

**Comment by andyguerra** [comment]
Do you already close the 
/

**Comment by andyguerra** [comment]
Please merge #3  first, remember to delete the branch and watch the video with attention before making another PR

**Review by andyguerra — CHANGES_REQUESTED** [review]
**Success**
Runtime: 179 ms, faster than 38.93% of C# online submissions for Two Sum.
Memory Usage: 44.6 MB, less than 40.63% of C# online submissions for Two Sum.

Try to make it less than O(n<sup>2</sup>)

This is the [video](https://www.youtube.com/watch?v=KLlXCFG5TnA)

**Comment by LoLProM** [comment]
Okay

**Review by andyguerra — CHANGES_REQUESTED** [review]
The solution in the commit
[Solution for 1-TwoSum](https://github.com/LoLProM/NeetCode/pull/9/commits/b651c2fdf0b6cd2f960ee6de8012d1cbaccdf99c)
[b651c2f](https://github.com/LoLProM/NeetCode/pull/9/commits/b651c2fdf0b6cd2f960ee6de8012d1cbaccdf99c)
do not work.

The solution in [I Fixed the solution for 1-TwoSums](https://github.com/LoLProM/NeetCode/pull/9/commits/a4401ed56bc50a79364d2d23b61200c8b572a9cb)
[a4401ed](https://github.com/LoLProM/NeetCode/pull/9/commits/a4401ed56bc50a79364d2d23b61200c8b572a9cb)
does works ok.
**Success**
Runtime: 152 ms, faster than 77.83% of C# online submissions for Two Sum.
Memory Usage: 44.4 MB, less than 49.95% of C# online submissions for Two Sum.

The last one, the one with the dictionary, did **NOT WORK:**

***Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 10
At System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
At Solution.TwoSum(Int32[] nums, Int32 target)
At __Driver__.Main(String[] args)***
Last executed input
[1,1,1,1,1,4,1,1,1,1,1,7,1,1,1,1,1]
11

**Review by andyguerra — APPROVED** [review]
**Success**
Runtime: 133 ms, faster than **99.21%** of C# online submissions for Two Sum.
Memory Usage: 44.5 MB, less than 49.95% of C# online submissions for Two Sum.

Look at the percentage in speed 👀 👍🏼, first solution, 38.93% faster, second solution 77.83% and this one, a crazy 99.21% 🚀 
As always, remember to watch the video

**Pull request merged**
